name: syspig
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  toast: ^0.3.0
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  logger: ^2.1.0
  flutter_localization: ^0.2.0
  intl: ^0.19.0
  win32: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
  - assets/images/logo.png
  - assets/images/logoBlack.png
  - assets/images/logoWhite.png
  - assets/data/data.json